from os import environ

ENTITY_POSTPROCESSOR_GRPC_PORT_DEFAULT = 5207
ENTITY_POSTPROCESSOR_GRPC_PORT = environ.get(
    "ENTITY_POSTPROCESSOR_GRPC_PORT", ENTITY_POSTPROCESSOR_GRPC_PORT_DEFAULT
)

ENTITY_POSTPROCESSOR_GRPC_ADDRESS_DEFAULT = "0.0.0.0"  # nosec B104
ENTITY_POSTPROCESSOR_GRPC_ADDRESS = environ.get(
    "ENTITY_POSTPROCESSOR_GRPC_ADDRESS", ENTITY_POSTPROCESSOR_GRPC_ADDRESS_DEFAULT
)
