from os import environ

ACTIVITY_POSTPROCESSOR_GRPC_PORT_DEFAULT = 5208
ACTIVITY_POSTPROCESSOR_GRPC_PORT = environ.get(
    "ACTIVITY_POSTPROCESSOR_GRPC_PORT", ACTIVITY_POSTPROCESSOR_GRPC_PORT_DEFAULT
)

ACTIVITY_POSTPROCESSOR_GRPC_ADDRESS_DEFAULT = "0.0.0.0"  # nosec B104
ACTIVITY_POSTPROCESSOR_GRPC_ADDRESS = environ.get(
    "ACTIVITY_POSTPROCESSOR_GRPC_ADDRESS", ACTIVITY_POSTPROCESSOR_GRPC_ADDRESS_DEFAULT
)
