# -*- coding: utf-8 -*-
# mypy: ignore-errors
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: changepoint.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hangepoint.proto\x12\x13\x61tlanteschangepoint\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n\x10\x43hangepointInput\x12\x0c\n\x04sogs\x18\x01 \x03(\x02\x12)\n\x05times\x18\x02 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\"p\n\x11\x43hangepointOutput\x12\x16\n\x0eis_changepoint\x18\x01 \x01(\x08\x12\x43\n\x12\x63hangepoint_reason\x18\x02 \x01(\x0e\x32\'.atlanteschangepoint.ChangepointReasons*\x8e\x01\n\x12\x43hangepointReasons\x12\x07\n\x03SOG\x10\x00\x12\x08\n\x04TIME\x10\x01\x12\x12\n\x0eNO_CHANGEPOINT\x10\x02\x12\x17\n\x13NOT_ENOUGH_MESSAGES\x10\x03\x12\x19\n\x15MAX_DURATION_EXCEEDED\x10\x04\x12\x1d\n\x19MAX_NUM_MESSAGES_EXCEEDED\x10\x05\x32v\n\x12\x43hangepointService\x12`\n\rIsChangepoint\x12%.atlanteschangepoint.ChangepointInput\x1a&.atlanteschangepoint.ChangepointOutput\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'changepoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGEPOINTREASONS']._serialized_start=267
  _globals['_CHANGEPOINTREASONS']._serialized_end=409
  _globals['_CHANGEPOINTINPUT']._serialized_start=75
  _globals['_CHANGEPOINTINPUT']._serialized_end=150
  _globals['_CHANGEPOINTOUTPUT']._serialized_start=152
  _globals['_CHANGEPOINTOUTPUT']._serialized_end=264
  _globals['_CHANGEPOINTSERVICE']._serialized_start=411
  _globals['_CHANGEPOINTSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
