name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest-m
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects for test cases
        run: git lfs checkout

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate into gcp
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{secrets.GOOGLE_CREDENTIALS }}
      - name: Build docker images
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ais/docker-compose.yml build
      - name: Run unit and integration tests
        run: |
          docker compose -f ais/docker-compose.yml run \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_activity pytest -n auto \
            --ignore=tests/test_main_activity.py \
            --ignore=tests/test_main_entity.py \
            --ignore=tests/integration/cpd/serve/test_serve_grpc.py \
            --ignore=tests/integration/inference/atlas_entity/ \
            --ignore=tests/integration/inference/atlas_activity/ \
            -vv
      - name: Run Pipeline tests
        run: |
          docker compose -f ais/docker-compose.yml run \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_entity pytest tests/integration/inference/atlas_entity/ \
            --ignore=tests/integration/inference/atlas_entity/grpc_serve/test_serve_grpc.py \
            -vv
          docker compose -f ais/docker-compose.yml run \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_activity pytest tests/integration/inference/atlas_activity/ -vv
      - name: Run service tests
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ais/docker-compose.yml up -d --wait
          sleep 20
          docker compose -f ais/docker-compose.yml exec -T \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_activity pytest tests/test_main_activity.py -vv
          docker compose -f ais/docker-compose.yml exec -T \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_entity pytest tests/test_main_entity.py -vv
          docker compose -f ais/docker-compose.yml exec -T \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_cpd_grpc pytest tests/integration/cpd/serve/test_serve_grpc.py -vv
          docker compose -f ais/docker-compose.yml exec -T \
            -e TEST_PROJECTS_FOLDER_PREFIX=${{ secrets.TEST_PROJECTS_FOLDER_PREFIX }} \
            test_entity_postprocessor_grpc pytest tests/integration/inference/atlas_entity/grpc_serve/test_serve_grpc.py -vv
